<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="5" passed="3">
  <reporter-output>
    <line>
      <![CDATA[D()]]>
    </line>
    <line>
      <![CDATA[C()]]>
    </line>
    <line>
      <![CDATA[A()]]>
    </line>
    <line>
      <![CDATA[A()]]>
    </line>
  </reporter-output>
  <suite name="Suite10" duration-ms="105" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="105" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
      <class name="firstt.TMFail">
        <test-method status="PASS" signature="D()[pri:0, instance:firstt.TMFail@763d9750]" name="D" duration-ms="15" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
          <reporter-output>
            <line>
              <![CDATA[D()]]>
            </line>
          </reporter-output>
        </test-method> <!-- D -->
        <test-method status="FAIL" signature="C()[pri:2, instance:firstt.TMFail@763d9750]" name="C" duration-ms="12" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at firstt.TMFail.C(TMFail.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[C()]]>
            </line>
          </reporter-output>
        </test-method> <!-- C -->
        <test-method status="SKIP" signature="B()[pri:1, instance:firstt.TMFail@763d9750]" name="B" duration-ms="0" started-at="2019-02-28T07:20:16Z" depends-on-methods="firstt.TMFail.C" finished-at="2019-02-28T07:20:16Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TMFail.B()[pri:1, instance:firstt.TMFail@763d9750] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TMFail.B()[pri:1, instance:firstt.TMFail@763d9750] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- B -->
        <test-method status="PASS" signature="A()[pri:3, instance:firstt.TMFail@763d9750]" name="A" duration-ms="3" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
          <reporter-output>
            <line>
              <![CDATA[A()]]>
            </line>
          </reporter-output>
        </test-method> <!-- A -->
        <test-method status="PASS" signature="A()[pri:3, instance:firstt.TMFail@763d9750]" name="A" duration-ms="2" started-at="2019-02-28T07:20:16Z" finished-at="2019-02-28T07:20:16Z">
          <reporter-output>
            <line>
              <![CDATA[A()]]>
            </line>
          </reporter-output>
        </test-method> <!-- A -->
      </class> <!-- firstt.TMFail -->
    </test> <!-- Test -->
  </suite> <!-- Suite10 -->
</testng-results>
